### ISSUE TITLE
Nose test error

### ISSUE THREAD

**Issue by bsamadi** [cvxgrp/cvxpy#305]
When I run nosetests cvxpy for cvxpy on Python 3, I get 26 errors and one failure. 
Some of the error messages complain about SCS not being installed and  an undefined symbol: GOMP_parallel. I was wondering how I can fix it.
                                                                                                                                   
```
======================================================================                                                             
ERROR: test_sdp_problem (cvxpy.tests.test_semidefinite_vars.TestSemidefiniteVariable)                                              
----------------------------------------------------------------------                                                             
Traceback (most recent call last):                                                                                                 
  File "/opt/conda/lib/python3.5/site-packages/cvxpy/tests/test_semidefinite_vars.py", line 46, in test_sdp_problem                
    result = p.solve()                                                                                                             
  File "/opt/conda/lib/python3.5/site-packages/cvxpy/problems/problem.py", line 201, in solve                                      
    return self._solve(*args, **kwargs)                                                                                            
  File "/opt/conda/lib/python3.5/site-packages/cvxpy/problems/problem.py", line 323, in _solve                                     
    kwargs)                                                                                                                        
  File "/opt/conda/lib/python3.5/site-packages/cvxpy/problems/solvers/scs_intf.py", line 96, in solve                              
    import scs                                                                                                                     
  File "/opt/conda/lib/python3.5/site-packages/scs-1.2.6-py3.5-linux-x86_64.egg/scs.py", line 4, in <module>                       
    import _scs_indirect                                                                                                           
ImportError: /opt/conda/lib/python3.5/site-packages/scs-1.2.6-py3.5-linux-x86_64.egg/_scs_indirect.cpython-35m-x86_64-linux-gnu.so:
 undefined symbol: GOMP_parallel    
======================================================================                                                             
FAIL: Tests that chaining constraints raises an error.                                                                             
----------------------------------------------------------------------                                                             
Traceback (most recent call last):                                                                                                 
  File "/opt/conda/lib/python3.5/site-packages/cvxpy/tests/test_constraints.py", line 242, in test_chained_constraints             
    self.assertEqual(str(cm.exception), error_str)                                                                                 
AssertionError: "'LeqConstraint' object has no attribute '__nonzero__'" != 'Cannot evaluate the truth value of a con[44 chars]= 0.'
- 'LeqConstraint' object has no attribute '__nonzero__'                                                                            
+ Cannot evaluate the truth value of a constraint or chain constraints, e.g., 1 >= x >= 0.         
```

**Comment by SteveDiamond** [comment]
Somebody else asked about this here: https://groups.google.com/forum/#!topic/cvxpy/cIYiUABZzVA
I suspect you have an old version of cvxpy. How did you install it?

**Comment by bsamadi** [comment]
I used:
conda install mkl
conda install -c cvxgrp cvxpy
conda install nose

**Comment by bsamadi** [comment]
You can try it here: 
https://hub.docker.com/r/bsamadi/cvxpy-notebook/

**Comment by bsamadi** [comment]
It seems that something is wrong with the numpy installation and it has to be reinstalled. I found the solution here:
https://github.com/ContinuumIO/anaconda-issues/issues/720

I added these commands after cvxpy and nose installation commands:
```# Reinstall numpy```
```RUN conda remove nomkl```
```RUN conda install mkl```
```RUN conda install -f  numpy```
```RUN conda remove -n python2 nomkl```
```RUN conda install -n python2 mkl```
```RUN conda install -n python2 -f  numpy```

Now, I can run all the 1730 tests in Python 2 successfully. In Python 3, I get only one failure:
/opt/conda/lib/python3.5/site-packages/dill/dill.py:149: ResourceWarning: unclosed file <_io.FileIO name='/dev/null' mode='rb' closefd=True>
  FileType = type(open(os.devnull, 'rb', buffering=0))
/opt/conda/lib/python3.5/site-packages/dill/dill.py:150: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='r' encoding='UTF-8'>
  TextWrapperType = type(open(os.devnull, 'r', buffering=-1))
/opt/conda/lib/python3.5/site-packages/dill/dill.py:151: ResourceWarning: unclosed file <_io.BufferedRandom name='/dev/null'>
  BufferedRandomType = type(open(os.devnull, 'r+b', buffering=-1))
/opt/conda/lib/python3.5/site-packages/dill/dill.py:152: ResourceWarning: unclosed file <_io.BufferedReader name='/dev/null'>
  BufferedReaderType = type(open(os.devnull, 'rb', buffering=-1))
/opt/conda/lib/python3.5/site-packages/dill/dill.py:153: ResourceWarning: unclosed file <_io.BufferedWriter name='/dev/null'>
  BufferedWriterType = type(open(os.devnull, 'wb', buffering=-1))

FAIL: Tests that chaining constraints raises an error.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/cvxpy/tests/test_constraints.py", line 242, in test_chained_constraints
    self.assertEqual(str(cm.exception), error_str)
AssertionError: "'LeqConstraint' object has no attribute '__nonzero__'" != 'Cannot evaluate the truth value of a con[44 chars]= 0.'
- 'LeqConstraint' object has no attribute '__nonzero__'
+ Cannot evaluate the truth value of a constraint or chain constraints, e.g., 1 >= x >= 0.

**Comment by SteveDiamond** [comment]
What is the output of "cvxpy.__version__"?

**Comment by bsamadi** [comment]
0.4.5
This is a fresh install using pip.

**Comment by SteveDiamond** [comment]
The current version is 0.4.6.

**Comment by bsamadi** [comment]
Will conda get the 0.4.6 version soon?

**Comment by SteveDiamond** [comment]
Oops, sorry. I thought it was on conda because I accidentally uploaded it to my personal channel instead of cvxgrp. The cvxgrp channel now has 0.4.6. Sorry about that.

**Comment by bsamadi** [comment]
Thank you. I still get 0.4.5 with conda. I should probably wait a couple of days.

**Comment by SteveDiamond** [comment]
Try ``conda install -c cvxgrp cvxpy=0.4.6``
You can see it's uploaded here: https://anaconda.org/cvxgrp/cvxpy

**Comment by bsamadi** [comment]
I get this error:
PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - cvxpy 0.4.6*

**Comment by SteveDiamond** [comment]
I forgot to upload linux versions. The test error was truly bizarre, due to a difference between pip install and conda build. Everything should work now if you install cvxpy 0.4.8.

**Comment by bsamadi** [comment]
Thank you for looking at this. With conda install -c cvxgrp cvxpy, conda on Linux installs the 0.4.8 version! and on Windows it installs the 0.4.2 version. 

I installed the 0.4.6 version with conda install -c cvxgrp cvxpy=0.4.6
The single failure in Python 3.5 is still the same. On Python 2.7, the tests run successfully.

FAIL: Tests that chaining constraints raises an error.                                                                                    
----------------------------------------------------------------------                                                                    
Traceback (most recent call last):                                                                                                        
  File "/opt/conda/lib/python3.5/site-packages/cvxpy/tests/test_constraints.py", line 242, in test_chained_constraints                    
    self.assertEqual(str(cm.exception), error_str)                                                                                        
AssertionError: "'LeqConstraint' object has no attribute '__nonzero__'" != 'Cannot evaluate the truth value of a con[44 chars]= 0.'       
- 'LeqConstraint' object has no attribute '__nonzero__'                                                                                   
+ Cannot evaluate the truth value of a constraint or chain constraints, e.g., 1 >= x >= 0.

**Comment by SteveDiamond** [comment]
Yes, you need to update to cvxpy 0.4.8 for the test error to go away. The
conda installation doesn't work on windows.
